-- Generated by scripts/generate-seed.ts from lib/__fixtures__/upper-lower.csv. Do not edit by hand:
-- change the parser or the CSV and run `pnpm seed:generate`.
--
-- Seeds one user's routines, exercises and imported workouts (docs/SPEC.md,
-- "Seed data"). Usage:
--   psql "$SUPABASE_DB_URL" -v email=you@example.com -f supabase/seed.sql
-- or the "Seed from Sheet" GitHub Actions workflow.

\set ON_ERROR_STOP 1
begin;
select set_config('seed.email', :'email', true) as seed_email \gset

do $seed$
declare
  uid uuid;
  p_id uuid;
  r_id uuid;
  w_id uuid;
  e_id uuid;
  n_exercises int := 0;
  n_sets int := 0;
begin
  select id into uid from auth.users where lower(email) = lower(current_setting('seed.email'));
  if uid is null then
    raise exception 'No user with email %. Sign up in the app first.', current_setting('seed.email');
  end if;

  if exists (select 1 from public.routines where user_id = uid) then
    raise notice 'User already has routines; nothing seeded.';
    return;
  end if;

  -- One plan holds the imported routines; active unless another plan is.
  insert into public.plans (user_id, name, is_custom, is_active)
  select uid,
         coalesce(nullif(trim(p.name), '') || '''s Upper Lower plan', 'My Upper Lower plan'),
         true,
         not exists (select 1 from public.plans where user_id = uid and is_active)
  from (select 1) as one
  left join public.profiles p on p.id = uid
  returning id into p_id;

  -- Push
  insert into public.routines (user_id, plan_id, name, sort_order)
    values (uid, p_id, 'Push', 0) returning id into r_id;
  insert into public.workouts (user_id, routine_id, started_at, ended_at, notes, source)
    values (uid, r_id, now(), now(), 'Imported from Google Sheet', 'sheet_import') returning id into w_id;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Incline Bench Press') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Incline Bench Press', 'strength', 'machine', array['chest', 'front delts', 'triceps']::text[], '5', false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 1, 3, 10);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 15, 0, 8);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Flat Bench Press') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Flat Bench Press', 'strength', 'machine', array['chest', 'front delts', 'triceps']::text[], null, false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 2, 3, 12);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 15, 0, 10);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Lateral Raise') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Lateral Raise', 'strength', 'cable', array['side delts']::text[], '16', false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 3, 3, 20);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 1.25, 0.6, 12);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Rear Delt Fly') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Rear Delt Fly', 'strength', 'machine', array['rear delts', 'upper back']::text[], null, false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 4, 3, 15);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 35, 0, 8);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Rope Triceps Extension') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Rope Triceps Extension', 'strength', 'cable', array['triceps']::text[], null, false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 5, 2, 15);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 8.75, 0, 12);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Cable Triceps Pressdown') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Cable Triceps Pressdown', 'strength', 'cable', array['triceps']::text[], null, false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 6, 2, 15);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 11.25, 0, 10);
  n_sets := n_sets + 1;

  -- Legs
  insert into public.routines (user_id, plan_id, name, sort_order)
    values (uid, p_id, 'Legs', 1) returning id into r_id;
  insert into public.workouts (user_id, routine_id, started_at, ended_at, notes, source)
    values (uid, r_id, now(), now(), 'Imported from Google Sheet', 'sheet_import') returning id into w_id;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Leg Press') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Leg Press', 'strength', 'machine', array['quads', 'glutes']::text[], null, false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 1, 4, 8);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 105, 0, 7);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Single-Leg Dumbbell RDL') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Single-Leg Dumbbell RDL', 'strength', 'dumbbell', array['hamstrings', 'glutes']::text[], null, true)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 2, 3, 8);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 7.5, 0, 6);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Hip Abduction') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Hip Abduction', 'strength', 'machine', array['abductors']::text[], null, false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 3, 3, 20);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 22.5, 3.75, 14);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Leg Extension') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Leg Extension', 'strength', 'machine', array['quads']::text[], '4', false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 4, 3, 15);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 57.5, 0, 13);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Seated Calf Raise') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Seated Calf Raise', 'strength', 'machine', array['calves']::text[], null, false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 5, 3, 20);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 10, 0, 12);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Pallof Press') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Pallof Press', 'strength', 'cable', array['core']::text[], '11', false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 6, 3, 15);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 11.25, 0, 10);
  n_sets := n_sets + 1;

  -- Upper 2
  insert into public.routines (user_id, plan_id, name, sort_order)
    values (uid, p_id, 'Upper 2', 2) returning id into r_id;
  insert into public.workouts (user_id, routine_id, started_at, ended_at, notes, source)
    values (uid, r_id, now(), now(), 'Imported from Google Sheet', 'sheet_import') returning id into w_id;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Lat Pulldown') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Lat Pulldown', 'strength', 'cable', array['lats', 'biceps']::text[], null, false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 1, 3, 10);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 23.5, 0, 7);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Machine Row') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Machine Row', 'strength', 'machine', array['upper back', 'lats', 'rear delts']::text[], '4', false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 2, 3, 12);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 35, 3.75, 9);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Incline Dumbbell Press') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Incline Dumbbell Press', 'strength', 'dumbbell', array['chest', 'front delts', 'triceps']::text[], null, true)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 3, 3, 12);
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Dumbbell Shoulder Press') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Dumbbell Shoulder Press', 'strength', 'dumbbell', array['front delts', 'side delts', 'triceps']::text[], null, true)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 4, 3, 12);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 10, 0, 8);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Biceps Curl') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Biceps Curl', 'strength', 'dumbbell', array['biceps']::text[], null, true)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 5, 2, 15);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 12.5, 0, 6);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Shrug') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Shrug', 'strength', 'dumbbell', array['traps']::text[], null, true)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 6, 2, 15);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 20, 0, 10);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Bayesian Curl') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Bayesian Curl', 'strength', 'cable', array['biceps']::text[], '16', false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 7, 2, 15);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 11.25, 0, 11);
  n_sets := n_sets + 1;

  -- Lower
  insert into public.routines (user_id, plan_id, name, sort_order)
    values (uid, p_id, 'Lower', 3) returning id into r_id;
  insert into public.workouts (user_id, routine_id, started_at, ended_at, notes, source)
    values (uid, r_id, now(), now(), 'Imported from Google Sheet', 'sheet_import') returning id into w_id;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Machine Hip Thrust') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Machine Hip Thrust', 'strength', 'machine', array['glutes', 'hamstrings']::text[], null, false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 1, 3, 10);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 60, 0, 5);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Walking Lunge') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Walking Lunge', 'strength', 'other', array['quads', 'glutes']::text[], null, true)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 2, 2, 12);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 15, 0, null);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Split Squat') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Split Squat', 'strength', 'dumbbell', array['quads', 'glutes']::text[], null, true)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 3, 2, 12);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 20, 0, 6);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Leg Curl') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Leg Curl', 'strength', 'machine', array['hamstrings']::text[], '4', false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 4, 3, 15);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 50, 3.75, 11);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Hip Adduction') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Hip Adduction', 'strength', 'machine', array['adductors']::text[], '6', false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 5, 3, 20);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 30, 3.75, 11);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Standing Single-Leg Calf Raise') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Standing Single-Leg Calf Raise', 'strength', 'dumbbell', array['calves']::text[], null, true)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 6, 3, 20);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', 10, 0, 13);
  n_sets := n_sets + 1;
  e_id := null;
  select id into e_id from public.exercises
    where user_id = uid and lower(name) = lower('Leg Raise') and archived_at is null;
  if e_id is null then
    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)
      values (uid, 'Leg Raise', 'strength', 'bodyweight', array['core']::text[], null, false)
      returning id into e_id;
    n_exercises := n_exercises + 1;
  end if;
  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)
    values (r_id, e_id, 7, 3, 15);
  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)
    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', null, 0, 10);
  n_sets := n_sets + 1;

  raise notice 'Seeded 4 routines, % new exercises, % sets.', n_exercises, n_sets;
end
$seed$;

commit;
