import type { ImportResult, LastSet } from "./sheet-import";

/**
 * Turns an import into supabase/seed.sql: one transaction that gives the user
 * named by psql variable `email` the routines, exercises and one
 * "Imported from Google Sheet" workout per routine.
 *
 * Safe to re-run: does nothing if the user already has routines, and reuses
 * an exercise that already exists under the same name.
 */
export function generateSeedSql(result: ImportResult, source: string): string {
  const body: string[] = [];

  for (const routine of result.routines) {
    body.push(
      ``,
      `  -- ${routine.name}`,
      `  insert into public.routines (user_id, name, sort_order)`,
      `    values (uid, ${lit(routine.name)}, ${routine.sortOrder}) returning id into r_id;`,
      `  insert into public.workouts (user_id, routine_id, started_at, ended_at, notes, source)`,
      `    values (uid, r_id, now(), now(), 'Imported from Google Sheet', 'sheet_import') returning id into w_id;`,
    );

    routine.exercises.forEach((ex, i) => {
      body.push(
        `  e_id := null;`,
        `  select id into e_id from public.exercises`,
        `    where user_id = uid and lower(name) = lower(${lit(ex.name)}) and archived_at is null;`,
        `  if e_id is null then`,
        `    insert into public.exercises (user_id, name, type, equipment, muscle_groups, machine_setting, per_hand)`,
        `      values (uid, ${lit(ex.name)}, 'strength', ${lit(ex.equipment)}, ${textArray(ex.muscleGroups)}, ${lit(ex.machineSetting)}, ${ex.perHand})`,
        `      returning id into e_id;`,
        `    n_exercises := n_exercises + 1;`,
        `  end if;`,
        `  insert into public.routine_exercises (routine_id, exercise_id, sort_order, target_sets, target_reps)`,
        `    values (r_id, e_id, ${i + 1}, ${ex.targetSets}, ${ex.targetReps});`,
      );
      if (ex.lastSet) body.push(insertSet(ex.lastSet));
    });
  }

  return `-- Generated by scripts/generate-seed.ts from ${source}. Do not edit by hand:
-- change the parser or the CSV and run \`pnpm seed:generate\`.
--
-- Seeds one user's routines, exercises and imported workouts (docs/SPEC.md,
-- "Seed data"). Usage:
--   psql "$SUPABASE_DB_URL" -v email=you@example.com -f supabase/seed.sql
-- or the "Seed from Sheet" GitHub Actions workflow.

\\set ON_ERROR_STOP 1
begin;
select set_config('seed.email', :'email', true) as seed_email \\gset

do $seed$
declare
  uid uuid;
  r_id uuid;
  w_id uuid;
  e_id uuid;
  n_exercises int := 0;
  n_sets int := 0;
begin
  select id into uid from auth.users where lower(email) = lower(current_setting('seed.email'));
  if uid is null then
    raise exception 'No user with email %. Sign up in the app first.', current_setting('seed.email');
  end if;

  if exists (select 1 from public.routines where user_id = uid) then
    raise notice 'User already has routines; nothing seeded.';
    return;
  end if;
${body.join("\n")}

  raise notice 'Seeded ${result.routines.length} routines, % new exercises, % sets.', n_exercises, n_sets;
end
$seed$;

commit;
`;
}

function insertSet(set: LastSet): string {
  return [
    `  insert into public.sets (id, user_id, workout_id, exercise_id, set_no, set_type, weight_kg, added_kg, reps)`,
    `    values (gen_random_uuid(), uid, w_id, e_id, 1, 'working', ${num(set.weightKg)}, ${set.addedKg}, ${num(set.reps)});`,
    `  n_sets := n_sets + 1;`,
  ].join("\n");
}

function lit(value: string | null): string {
  return value === null ? "null" : `'${value.replace(/'/g, "''")}'`;
}

function num(value: number | null): string {
  return value === null ? "null" : String(value);
}

function textArray(values: string[]): string {
  return values.length ? `array[${values.map(lit).join(", ")}]::text[]` : `'{}'::text[]`;
}
